name: BoatMod
main: me.Jackpot.BoatMod.BoatMod
version: 5
commands:
   boatmod:
      description: This command controls BoatMod's script engine.
      usage: /boatmod [script name]
      permissions: boatmod.script