name: BoatMod
main: me.Jackpot.BoatMod.BoatMod
version: 7
commands:
   boatscript:
      description: This command controls BoatMod's script engine.
      usage: /boatscript [script name]
   boatspeed:
      description: This command controls BoatMod's script engine.
      usage: /boatspeed [speed]