name: BoatMod
main: me.Jackpot.BoatMod.BoatMod
version: 13
author: jackpot51
commands:
   boat:
      description: This command gives information about BoatMod.
      usage: /boat <auto [start, stop], script [script name], speed [speed]>
